SocialNetworkWithIdentity/SocialNetworkWithIdentity/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AutoMapper;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SocialNetworkWithIdentity.Models.DomainModels;
using SocialNetworkWithIdentity.Models.ViewModels;
using SocialNetworkWithIdentity.Services;

namespace SocialNetworkWithIdentity.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        // как и другие контроллеры, содержит в себе вот такой сервис
        private readonly PeopleService peopleService;

        public EventController()
        {
            peopleService = new PeopleService();
        }
        // GET: Event
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AllEvents()
        {
            var Events = peopleService.GetAllEventsFromUser(User.Identity.GetUserId()).OrderByDescending(d => d.Date);

            return View(Events);
        }

        public ActionResult RecordsOnTheWall(string UserId)
        {
            var Events =
                peopleService.GetAllEventsFromUser(UserId)
                    .Where(e => e.EventType == EventType.RecordOnTheWall).ToList();

            var Events1 = Events.Where(e => e.Sender.Id == UserId && (e.Owners.Count == 1)).ToList();
            var Events2 = Events.Where(e => e.Sender.Id != UserId).ToList();
            Events1.AddRange(Events2);
            return PartialView("AllEvents", Events1.OrderByDescending(d => d.Date));
        }

        [HttpPost]
        public ActionResult RecordOnTheWall(string senderUserId, string recieverUserId, string TextOnTheWall)
        {
            var keys = Request.Form.Keys;
            var _event = new Event
            {
                Sender = peopleService.GetUser(senderUserId),
                Text = TextOnTheWall,

                Date = DateTime.Now,
                Image = null,
                EventType = EventType.RecordOnTheWall,
                Owners = { peopleService.GetUser(senderUserId), peopleService.GetUser(recieverUserId) }
            };
            peopleService.MakeEvent(_event);
            return PartialView("AllEvents", peopleService.GetAllEventsFromUser(recieverUserId).Where(e => e.EventType == EventType.RecordOnTheWall).OrderByDescending(d => d.Date));
        }
    }
}

SocialNetworkWithIdentity/SocialNetworkWithIdentity/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SocialNetworkWithIdentity.Models;
using SocialNetworkWithIdentity.Models.DomainModels;
using SocialNetworkWithIdentity.Models.ViewModels;
using SocialNetworkWithIdentity.Services;
using AutoMapper;

namespace SocialNetworkWithIdentity.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
		private PeopleService peopleService = new PeopleService();

        public ActionResult SendFirstMessage(string receivedUserId)
		{
			var user = peopleService.GetUser(receivedUserId);
			var viewUser = Mapper.Map<ApplicationUser, FirstMessageViewModel>(user);
			return PartialView(viewUser);
		}

		[HttpPost]
		public ActionResult SendFirstMessage(FirstMessageViewModel messageModel)
		{
			var currentUser = peopleService.GetUser(User.Identity.GetUserId());

			var message = new Message
			{
				Date = DateTime.Now,
				Text = messageModel.Message,
				Sender = currentUser
			};

			peopleService.MakeMessage(message, peopleService.GetUser(messageModel.Id));

			return Redirect(HttpContext.Request.UrlReferrer.ToString());
		}

		[HttpPost]
		public ActionResult SendDialogMessage(string resiver, string messageText)
		{
			var currentUser = peopleService.GetUser(User.Identity.GetUserId());

			var message = new Message
			{
				Date = DateTime.Now,
				Text = messageText,
				Sender = currentUser
			};

			peopleService.MakeMessage(message, peopleService.GetUser(resiver));

			var room = peopleService.GetRoom(message, peopleService.GetUser(resiver));
			var Messages = peopleService.GetAllMessagesOfRoom(Convert.ToInt32(room.Id)).OrderBy(s => s.Date);
			var newMessages = Messages.Where(m => m.StatusForMessage == false && m.Sender.Id != User.Identity.GetUserId());
            foreach (var item in newMessages)
            {
				item.StatusForMessage = true;
            }
            peopleService.UnitOfWork.Save();

			return PartialView("EmptyView", Messages);
		}

		public ActionResult ShowAllDialogues()
		{
			var currentUser = peopleService.GetUser(User.Identity.GetUserId());
			var userRooms = peopleService.GetRooms().Where(u => u.Users.Contains(currentUser));
			var lastMessages = new List<Message>();

			foreach(var room in userRooms)
			{
			    var message = room.Messages.OrderBy(d => d.Date).LastOrDefault();

			    if (message.Text.Length > 50)
			        message.Text = message.Text.Substring(0, 50) + "...";

				lastMessages.Add(message);
			}

            return View(lastMessages.OrderByDescending(d => d.Date));
		}

        public ActionResult ShowAllMessagesOfRoom(string roomId)
        {
            var Messages = peopleService.GetAllMessagesOfRoom(Convert.ToInt32(roomId)).OrderBy(s => s.Date);
			var newMessages = Messages.Where(m => m.StatusForMessage == false && m.Sender.Id != User.Identity.GetUserId());
            foreach (var item in newMessages)
            {
				item.StatusForMessage = true;
            }
            peopleService.UnitOfWork.Save();
            return View(Messages);
        }
	}
}

SocialNetworkWithIdentity/SocialNetworkWithIdentity/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using SocialNetworkWithIdentity.Models;
using SocialNetworkWithIdentity.Models.DomainModels;
using SocialNetworkWithIdentity.Models.ViewModels;
using SocialNetworkWithIdentity.Services;

namespace SocialNetworkWithIdentity.Controllers
{
    [Authorize]
    // контроллер, где будут методы для взаимодействия с другими пользователями
    public class PeopleController : Controller
    {
        // как и другие контроллеры, содержит в себе вот такой сервис
        private readonly PeopleService peopleService;

        public PeopleController()
        {
            peopleService = new PeopleService();
        }

        // GET: People
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowUsers(string choice)
        {
            var users = peopleService.GetUsers();

            switch (choice)
            {
                case "Male":
                    users = peopleService.GetUsers().Where(u => u.Gender == true).ToList();
                    break;
                case "Female":
                    users = peopleService.GetUsers().Where(u => u.Gender == false).ToList();
                    break;
                default:
                    users = peopleService.GetUsers().ToList();
                    break;
            }

            // получить себя
            var currentUser = peopleService.GetUser(User.Identity.GetUserId());

            List<PeopleViewModel> ViewUsers = new List<PeopleViewModel>();

            //var users = peopleService.GetUsers();

            // Маппим коллекцию ApplicationUser-ов в коллекцию PeopleViewModel-ов
            ViewUsers = Mapper.Map<IEnumerable<ApplicationUser>, List<PeopleViewModel>>(users);

            foreach (var user in ViewUsers)
            {
                user.IsFriend = peopleService.CheckIfUserIsMyFriend(currentUser.Id, peopleService.GetUser(user.Id).Id);
                user.IsThereNewOfferFriendshipFromUserToMe = peopleService.CheckIfThereIsNewOfferFriendshipFromUserToMe(currentUser.Id, peopleService.GetUser(user.Id).Id);
                user.IsThereNewOfferFriendshipFromMeToUser = peopleService.CheckIfThereIsNewOfferFriendshipFromMeToUser(currentUser.Id, peopleService.GetUser(user.Id).Id);
            }

            return View(ViewUsers);
        }

        public ActionResult ShowFriendsOrOffers()
        {
            var getCountOffersFriendships = peopleService.GetCountOffersFriendships(User.Identity.GetUserId());

            if (getCountOffersFriendships > 0)
                return OfferfriendshipList();
            else
                return FriendshipList(User.Identity.GetUserId());
        }

        // Вью с приглашениями в друзья
        public ActionResult OfferfriendshipList()
        {
            var viewUsers = peopleService.GetAllFriendshipOffers(User.Identity.GetUserId());
            return View("OfferfriendshipList", viewUsers);
        }

        public ActionResult FriendshipList(string id)
        {
            ViewBag.UserId = id;
            var friends = peopleService.GetAllFriends(id);
            return View("FriendshipList", friends);
        }

        public ActionResult FriendsOnlineList(string id)
        {
            ViewBag.UserId = id;
            var friendsOnline = peopleService.GetAllFriendsOnline(id);
            return View("FriendsOnlineList", friendsOnline);
        }

        public ActionResult CommonFriendshipList(string id)
        {
            ViewBag.UserId = id;
            var friends = peopleService.GetAllCommonFriends(User.Identity.GetUserId(), id);
            return View("CommonFriendshipList", friends);
        }

        #region Работа с Дружбой (AJAX)
        // Отправляем заявку в друзья (AJAX)
        [HttpPost]
        public ActionResult SendOfferFriendship(string friendId)
        {
            if (peopleService.MakeOfferFriendship(User.Identity.GetUserId(), friendId))
            {
                var _event = new Event
                {
                    Sender = peopleService.GetUser(User.Identity.GetUserId()),
                    Text = peopleService.GetUser(User.Identity.GetUserId()).Name +
                    (peopleService.GetUser(User.Identity.GetUserId()).Gender == true ? " пригласил " : " пригласила ")
                    + peopleService.GetUser(friendId).Name + " в друзья.",
                    Date = DateTime.Now,
                    Image = null,
                    EventType = EventType.OfferFriendship,
                    Owners = { peopleService.GetUser(User.Identity.GetUserId()), peopleService.GetUser(friendId) }
                };

                peopleService.MakeEvent(_event);
                ViewBag.Result = "Заявка в друзья отправлена.";
            }
            else
            {
                ViewBag.Result = "Что-то пошло не так";
            }

            //return Redirect(HttpContext.Request.UrlReferrer.ToString());
            return PartialView("FriendshipButtonStatus", friendId);
        }

        // Удаляем из друзей (AJAX)
        [HttpPost]
        public ActionResult DeleteFriendship(string friendId)
        {
            if (peopleService.DeleteFriendship(User.Identity.GetUserId(), friendId))
            {
                var _event = new Event
                {
                    Sender = peopleService.GetUser(User.Identity.GetUserId()),
                    Text = peopleService.GetUser(User.Identity.GetUserId()).Name +
                    (peopleService.GetUser(User.Identity.GetUserId()).Gender == true ? " удалил " : " удалила ")
                    + " пользователя " + peopleService.GetUser(friendId).Name + " из списка своих друзей.",

                    Date = DateTime.Now,
                    Image = null,
                    EventType = EventType.DeleteFriendship,
                    Owners = { peopleService.GetUser(User.Identity.GetUserId()), peopleService.GetUser(friendId) }
                };
                peopleService.MakeEvent(_event);
                ViewBag.Result = "Удаление из друзей произведено";
            }
            else
            {
                ViewBag.Result = "Что-то пошло не так";
            }

            return PartialView("FriendshipButtonStatus", friendId);
        }

        // Подтверждаем заявку в друзья (AJAX)
        [HttpPost]
        public ActionResult ConfirmOfferFriendship(string friendId)
        {
            if (peopleService.CreateNewFriendship(User.Identity.GetUserId(), friendId))
            {
                var _event = new Event
                {
                    Sender = peopleService.GetUser(User.Identity.GetUserId()),
                    Text = peopleService.GetUser(User.Identity.GetUserId()).Name +
                    (peopleService.GetUser(User.Identity.GetUserId()).Gender == true ? " подтвердил " : " подтвердила ")
                    + "заявку в друзья от пользователя " + peopleService.GetUser(friendId).Name + ".",

                    Date = DateTime.Now,
                    Image = null,
                    EventType = EventType.ConfirmFriendship,
                    Owners = { peopleService.GetUser(User.Identity.GetUserId()), peopleService.GetUser(friendId) }
                };
                peopleService.MakeEvent(_event);
                ViewBag.Result = "Заявка принята";
            }
            else
            {
                ViewBag.Result = "Что-то пошло не так";
            }

            //return Redirect(HttpContext.Request.UrlReferrer.ToString());
            return PartialView("FriendshipButtonStatus", friendId);
        }

        // Отклоняем заявку в друзья (AJAX)
        [HttpPost]
        public ActionResult DontConfirmOfferFriendship(string friendId)
        {
            if (peopleService.CancelOfferFriendship(friendId, User.Identity.GetUserId()))
            {
                var _event = new Event
                {
                    Sender = peopleService.GetUser(User.Identity.GetUserId()),
                    Text = peopleService.GetUser(User.Identity.GetUserId()).Name +
                    (peopleService.GetUser(User.Identity.GetUserId()).Gender == true ? " отклонил " : " отклонила ")
                    + "заявку в друзья от пользователя " + peopleService.GetUser(friendId).Name + ".",

                    Date = DateTime.Now,
                    Image = null,
                    EventType = EventType.DontConfirmOfferFriendship,
                    Owners = { peopleService.GetUser(User.Identity.GetUserId()), peopleService.GetUser(friendId) }
                };
                peopleService.MakeEvent(_event);
                ViewBag.Result = "Заявка в друзья отклонена.";
            }
            else
            {
                ViewBag.Result = "Что-то пошло не так";
            }

            //return Redirect(HttpContext.Request.UrlReferrer.ToString());
            return PartialView("FriendshipButtonStatus", friendId);
        }

        // Отменяем заявку в друзья (AJAX)
        [HttpPost]
        public ActionResult CancelOfferFriendship(string friendId)
        {
            if (peopleService.CancelOfferFriendship(User.Identity.GetUserId(), friendId))
            {
                var _event = new Event
                {
                    Sender = peopleService.GetUser(User.Identity.GetUserId()),
                    Text = peopleService.GetUser(User.Identity.GetUserId()).Name +
                    (peopleService.GetUser(User.Identity.GetUserId()).Gender == true ? " отменил " : " отменила ")
                    + "заявку в друзья к пользователю " + peopleService.GetUser(friendId).Name + ".",

                    Date = DateTime.Now,
                    Image = null,
                    EventType = EventType.CancelOfferfriendship,

SocialNetworkWithIdentity/SocialNetworkWithIdentity/Views/Shared/CheckUserPageOfFriendOrAnotherPerson.cshtml
@using Microsoft.AspNet.Identity
@using SocialNetworkWithIdentity.Services

@model string

@{
    PeopleService peopleService = new PeopleService();
}

<div id="userLink_@Model">
    @if (peopleService.CheckIfUserIsMyFriend(User.Identity.GetUserId(), Model))
    {
        <a href="../Account/UserPageOfFriend?Id=@Model">
            <p>@Html.DisplayFor(modelItem => peopleService.GetUser(Model).Name)&nbsp;@Html.DisplayFor(modelItem => peopleService.GetUser(Model).Surname)</p>
        </a>
        <a class="forImage" href="../Account/UserPageOfFriend?Id=@Model">
            <img src='@Url.Content("~/Content/Images/AccountImages/" + peopleService.GetUser(Model).Avatar)' alt="Picture" width="100" height="100" />
        </a>
    }
    else
    {
        @*@Html.ActionLink(@Html.DisplayFor(modelItem => peopleService.GetUser(Model).Name) + " " + @Html.DisplayFor(modelItem => peopleService.GetUser(Model).Surname),
                                         "UserPageOfAnotherPerson", "Account", new { Id = Model }, null)*@
        <a href="../Account/UserPageOfAnotherPerson?Id=@Model">
            <p>@Html.DisplayFor(modelItem => peopleService.GetUser(Model).Name)&nbsp;@Html.DisplayFor(modelItem => peopleService.GetUser(Model).Surname)</p>
        </a>
        <a class="forImage" href="../Account/UserPageOfAnotherPerson?Id=@Model">
            <img src='@Url.Content("~/Content/Images/AccountImages/" + peopleService.GetUser(Model).Avatar)' alt="Picture" width="100" height="100" />
        </a>
    }
</div>

SocialNetworkWithIdentity/SocialNetworkWithIdentity/Views/Shared/SmallUserLink_1.cshtml
@using Microsoft.AspNet.Identity
@using SocialNetworkWithIdentity.Services
@model string
@{
    PeopleService peopleService = new PeopleService();
}


<div style="background-color: #DBD7D7; border-radius: 3px; padding: 5px;">
    <a href="/Account/UserPage/@Model">
        <img src='@Url.Content("~/Content/Images/AccountImages/" + peopleService.GetUser(Model).Avatar)' alt="Avatar" width="40" height="40" />
    </a>
    <div>
        <a href="/Account/UserPage/@peopleService.GetUser(Model).Id">
            @{ ViewBag.userName = @peopleService.GetUser(Model).Name; }
            @if (@peopleService.GetUser(Model).Name.Length > 9)
            {
                ViewBag.userName = @peopleService.GetUser(Model).Name.Remove(7);
                ViewBag.userName += "...";
            }
            @{ ViewBag.userSurName = @peopleService.GetUser(Model).Surname; }
            @if (@peopleService.GetUser(Model).Surname.Length > 9)
            {
                ViewBag.userSurName = @peopleService.GetUser(Model).Surname.Remove(7);
                ViewBag.userSurName += "...";
            }
            <p style="font-size: 12px">@ViewBag.userName</p>
            <p style="font-size: 12px; margin-top: -15px;">@ViewBag.userSurName</p>
        </a>
    </div>
</div>

SocialNetworkWithIdentity/SocialNetworkWithIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Social Network</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/scripts")

    <!--Иконка брэнда в адресной страке -->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    @*<a href="@Url.Action("Index")">
        <img src="/favicon.ico" alt="" />
    </a>*@
    <style>
        .menu {
            position: fixed;
        }

        .text {
            height: 1000px;
        }
    </style>
</head>
<body>
    <!--Верхняя панель меню-->
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: DarkSlateGray ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--Иконка брэнда на странице -->
                <a href="@Url.Action("Index")">
                <img class="img-responsive" alt="Brand" src="/favicon.ico" width="64" height="64" align="left"/>
                </a>
                @Html.ActionLink("Social Network", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Поиск...">
                    </div>
                    <button type="submit" class="btn btn-default glyphicon glyphicon-search"></button>
                </form>
                <ul class="nav navbar-nav">
                    <!--Ссылка на страницу пользователя с текстом "имя пользователя"-->
                    @*<li class="visible-xs"><a href="../Account/UserPage">Моя страница</a></li>*@
                    <li class="visible-xs">@Html.ActionLink("Моя страница", "UserPage", "Account")</li>
                    <li class="visible-xs"><a href="../Home/About">Друзья <span class="badge">0</span></a></li>
                    <li class="visible-xs">@Html.ActionLink("Сообщения", "Message", "ShowAllMessage")</li>
                    <li class="visible-xs"><a href="../Home/About">Фотографии</a></li>
                    <li class="visible-xs"><a href="../Home/About">Новости <span class="badge">0</span></a></li>
                    @*<li class="hidden-xs">@Html.ActionLink(" UserName", "Index", "Home", new { @class = "glyphicon glyphicon-user" })</li>*@
                    <li>@Html.ActionLink("Пользователи", "ShowUsers", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.Partial("_LoginPartial")</li>
                    <li class="hidden-lg">@Html.ActionLink("Выйти", "Contact", "Home")</li>
                    @*<li class="col-md-push-4 visible-lg">@Html.ActionLink("Выйти", "Contact", "Home")</li>*@
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <br />
        <div class="container-fluid">
            <!--Боковая панель меню-->
            <div class="row-fluid">
                <div class="col-md-2 hidden-xs">
                    <ul class=" nav nav-list menu">
                        @*<li><a href="../Account/UserPage">Моя страница</a></li>*@
                        <li>@Html.ActionLink("Моя страница", "UserPage", "Account")</li>
                        <li>@Html.ActionLink("Друзья", "OfferfriendshipList", "People")<span class="badge">@if(ViewBag.GetCountOffersFriendships > 0){@ViewBag.GetCountOffersFriendships}</span></li>
                        <li><a href="../Home/About">Сообщения <span class="badge">0</span></a></li>
                        <li><a href="../Home/About">Фотографии</a></li>
                        <li><a href="../Home/About">Новости <span class="badge">0</span></a></li>
                    </ul>
                </div>
                <!--Контент-->
                <div class="col-md-10">
                    <div class="container body-content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--<div class="container body-content">
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - RightTrueTeam</p>
        </footer>
    </div>-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SocialNetworkWithIdentity/SocialNetworkWithIdentity/Views/Shared/_LayoutMain.cshtml
@using Microsoft.AspNet.Identity
@using SocialNetworkWithIdentity.Services
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/scripts")
    <!--Иконка брэнда в адресной страке -->
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">

    @{
        PeopleService peopleService = new PeopleService();

        if (User != null)
        {
            ViewBag.CountOffersFriendships = peopleService.GetCountOffersFriendships(User.Identity.GetUserId());
            ViewBag.CountOfNewMessages = peopleService.GetCountOfDialoguesWithNewMessages(User.Identity.GetUserId());
            peopleService.SetDateOfActivity(User.Identity.GetUserId());
        }
    }
    <style>
        .headMenu
        {
            font-size: 18px;
            color: white;
        }
     </style>

</head>
<body>

    <div id="ShowWelcome" style="position: absolute; top: 0px; left: 100px; display: none; z-index: 9999;">
        <img style="width: 1200px; z-index: 9999;" src="~/Content/Images/AccountImages/Welcome.gif" />
    </div> 

    <!--Верхняя панель меню-->
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #2569B6; ">
        <div class="container headMenu">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span> <!--белые полоски справа в navbar, на которые можно нажать-->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--Иконка брэнда на странице -->
                <img class="img-responsive" alt="Brand" src="~/favicon.ico" width="64" height="64" align="left" />
                @Html.ActionLink("Социальная сеть", "About", "Home", null, new { @class = "navbar-brand", @style = "font-size: 25px;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="visible-xs">
                        <a href="/Account/UserPage">
                            Моя&nbsp;страница
                        </a>
                    </li>
                    <li class="visible-xs">
                        <a href="/People/ShowFriendsOrOffers">
                            Друзья
                            @if (ViewBag.CountOffersFriendships > 0)
                            {
                                <span class="badge span_friends">@ViewBag.CountOffersFriendships</span>
                            }
                        </a>
                    </li>
                    <li class="visible-xs">
                        <!--ставит циферку рядом справа, а не под словом, пришлось поменять хелпер на ссылку-->
                        <a href="/Message/ShowAllDialogues">
                            Сообщения
                            @if (ViewBag.CountOfNewMessages > 0)
                            {
                                <span class="badge span_messages">@ViewBag.CountOfNewMessages</span>
                            }
                        </a>
                    </li>
                    <li class="visible-xs">@Html.ActionLink("Новости", "AllEvents", "Event")</li>
                    

                    @*<li>@Html.ActionLink("О программе", "About", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartialLogOff")
                <ul class="nav navbar-nav navbar-right">
                    <li class="visible-xs"><hr style="border-color: black; margin-top: -1px;" /></li>
                    <li>@Html.ActionLink("Пользователи", "ShowUsers", "People", null, new {@class = "headMenu"})</li>
                    <li>@Html.ActionLink("О программе", "About", "Home", null, new {@class = "headMenu"})</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <br />
        <div class="container-fluid">
            <!--Боковая панель меню-->
            <div class="row-fluid row">
                <div class="col-lg-2 col-md-2 hidden-xs col-sm-1" style="font-weight:bold">
                    <ul class=" nav nav-list menu">

                        <li>
                            <a href="/Account/UserPage">
                                Моя&nbsp;страница
                            </a>
                        </li>
                        <li>
                            <a href="/People/ShowFriendsOrOffers">
                                Друзья
                                    @if (ViewBag.CountOffersFriendships > 0)
                                    {
                                        <span class="badge span_friends">@ViewBag.CountOffersFriendships</span>
                                    }
                        </a>
                    </li>
                    <li>
                        <!--ставит циферку рядом справа, а не под словом, пришлось поменять хелпер на ссылку-->
                        <a href="/Message/ShowAllDialogues">
                            Сообщения
                            @if (ViewBag.CountOfNewMessages > 0)
                            {<span class="badge span_messages">@ViewBag.CountOfNewMessages</span>}
                    </a>
                </li>
                <li>@Html.ActionLink("Новости", "AllEvents", "Event")</li>
            </ul>
            </div>
                <!--Контент-->
                <div class="col-lg-offset-1  col-lg-9 col-md-9 col-sm-9 col-sm-offset-1">
                    <div class="body-content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content navbar-fixed-bottom">

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>